# Generated by Django 4.0.3 on 2022-09-02 12:18

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProductCategoryModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categoryName', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='ProductModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('productName', models.CharField(max_length=255)),
                ('quantity', models.IntegerField()),
                ('price', models.FloatField(max_length=7)),
                ('packagingQuantity', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('product_image', models.ImageField(upload_to='product_images/')),
                ('productCategory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.productcategorymodel')),
            ],
        ),
    ]
