# Generated by Django 4.0.3 on 2022-11-07 10:23

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PackagingMetric',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('packagingMetric', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='PackagingQuantity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('packagingQuantity', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='ProductCategoryModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categoryName', models.CharField(max_length=255)),
                ('ProductCategory_image', models.ImageField(default='media/product_images/Screenshot_2022-09-12_at_16.00.36.png', upload_to='productCategory_images/')),
            ],
        ),
        migrations.CreateModel(
            name='ProductNameModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('productName', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='ProductsModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('productPrice', models.IntegerField()),
                ('productPieces', models.IntegerField()),
                ('productImage', models.ImageField(default='media/product_images/Screenshot_2022-09-12_at_16.00.36.png', upload_to='product_images/')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('packagingMetric', models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, to='product.packagingmetric')),
                ('packagingQuantity', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='product.packagingquantity')),
                ('productCategory', models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, to='product.productcategorymodel')),
            ],
        ),
    ]
