# Generated by Django 4.0.3 on 2022-09-22 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manufacturer', '0002_manufactureregistermodel_email'),
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductNameModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('productName', models.CharField(max_length=255)),
            ],
        ),
        migrations.AddField(
            model_name='productmodel',
            name='manufacturer',
            field=models.ManyToManyField(to='manufacturer.manufactureregistermodel'),
        ),
        migrations.RemoveField(
            model_name='productmodel',
            name='productName',
        ),
        migrations.AddField(
            model_name='productmodel',
            name='productName',
            field=models.ManyToManyField(to='product.productnamemodel'),
        ),
    ]
