# Generated by Django 4.0.3 on 2022-10-18 11:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('manufacturer', '0002_manufactureregistermodel_email'),
        ('product', '0002_productnamemodel_productmodel_manufacturer_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='productnamemodel',
            name='ProductCategory_image',
            field=models.ImageField(default=1, upload_to='productCategory_images/'),
        ),
        migrations.RemoveField(
            model_name='productmodel',
            name='manufacturer',
        ),
        migrations.AddField(
            model_name='productmodel',
            name='manufacturer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='manufacturer.manufactureregistermodel'),
        ),
        migrations.AlterField(
            model_name='productmodel',
            name='productCategory',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='product.productcategorymodel'),
        ),
    ]
