# Generated by Django 4.0.3 on 2022-10-18 11:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_productnamemodel_productcategory_image_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productnamemodel',
            old_name='productName',
            new_name='Name',
        ),
    ]
