# Generated by Django 4.0.3 on 2022-10-18 11:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0004_rename_productname_productnamemodel_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productnamemodel',
            old_name='Name',
            new_name='CategoryName',
        ),
    ]
