# Generated by Django 4.0.3 on 2022-10-18 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0005_rename_name_productnamemodel_categoryname'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productnamemodel',
            old_name='CategoryName',
            new_name='productName',
        ),
        migrations.RemoveField(
            model_name='productnamemodel',
            name='ProductCategory_image',
        ),
        migrations.AddField(
            model_name='productcategorymodel',
            name='ProductCategory_image',
            field=models.ImageField(default=1, upload_to='productCategory_images/'),
        ),
    ]
