# Generated by Django 4.0.3 on 2022-10-18 17:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0007_alter_productmodel_packagingquantity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productmodel',
            name='packagingQuantity',
            field=models.CharField(choices=[('kg', 'Kilogram'), ('mg', 'Milligrams'), ('ltr', 'Litre'), ('ml', 'Milliliter')], default='kg', max_length=3),
        ),
        migrations.RemoveField(
            model_name='productmodel',
            name='productName',
        ),
        migrations.AddField(
            model_name='productmodel',
            name='productName',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='product.productnamemodel'),
        ),
    ]
