# Generated by Django 4.0.3 on 2022-10-18 17:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0008_alter_productmodel_packagingquantity_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='packagingMetric',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('packagingQuantity', models.CharField(max_length=255)),
            ],
        ),
        migrations.RemoveField(
            model_name='productmodel',
            name='packagingQuantity',
        ),
        migrations.AddField(
            model_name='productmodel',
            name='packagingMetric',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='product.packagingmetric'),
        ),
    ]
