# Generated by Django 4.0.3 on 2022-10-18 17:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0009_packagingmetric_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='packagingmetric',
            old_name='packagingQuantity',
            new_name='packagingMetric',
        ),
    ]
