# Generated by Django 4.0.3 on 2022-10-21 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0010_rename_packagingquantity_packagingmetric_packagingmetric'),
    ]

    operations = [
        migrations.AddField(
            model_name='productmodel',
            name='PackagingQuantity',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
    ]
