# Generated by Django 4.0.3 on 2022-10-24 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0011_productmodel_packagingquantity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productcategorymodel',
            name='ProductCategory_image',
            field=models.ImageField(default='media/product_images/Screenshot_2022-09-12_at_16.00.36.png', upload_to='productCategory_images/'),
        ),
    ]
