# Generated by Django 4.0.3 on 2022-10-24 08:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0012_alter_productcategorymodel_productcategory_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productmodel',
            name='packagingMetric',
        ),
    ]
