# Generated by Django 4.0.3 on 2022-10-24 08:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('product', '0013_remove_productmodel_packagingmetric'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductsModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('productPrice', models.IntegerField()),
                ('productCategory', models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, to='product.productcategorymodel')),
                ('productManufacturer', models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, to=settings.AUTH_USER_MODEL)),
                ('productName', models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, to='product.productnamemodel')),
            ],
        ),
    ]
