# Generated by Django 4.0.3 on 2022-10-24 08:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0015_productsmodel_productimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='productsmodel',
            name='packagingMetric',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, to='product.packagingmetric'),
        ),
    ]
