# Generated by Django 4.0.3 on 2022-10-24 08:55

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0016_productsmodel_packagingmetric'),
    ]

    operations = [
        migrations.AddField(
            model_name='productsmodel',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
