# Generated by Django 4.0.3 on 2022-10-24 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0017_productsmodel_created_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='PackagingQuantity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('packagingQuantity', models.IntegerField()),
            ],
        ),
    ]
