# Generated by Django 4.0.3 on 2022-09-22 12:39

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('installments', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentLogModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.FloatField(max_length=7)),
                ('totalAmountPaid', models.FloatField(max_length=7)),
                ('balance', models.FloatField(max_length=7)),
                ('timePaid', models.DateTimeField(auto_now_add=True)),
                ('paymentMethod', models.CharField(max_length=255)),
                ('installment_id', models.ManyToManyField(to='installments.installmentmodel')),
                ('user_id', models.ManyToManyField(to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
