# Generated by Django 4.0.3 on 2022-11-07 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('finance', '0001_initial'),
        ('installments', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentlogmodel',
            name='installment_id',
            field=models.ManyToManyField(to='installments.installmentnumbermodel'),
        ),
    ]
