# Generated by Django 4.0.3 on 2022-11-07 10:23

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('finance', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentlogmodel',
            name='user_id',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
    ]
