# Generated by Django 4.0.3 on 2022-11-16 08:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('installments', '0005_cart_quantity'),
        ('finance', '0005_remove_paymentlogmodel_user_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='paymentlogmodel',
            name='installment_id',
        ),
        migrations.AddField(
            model_name='paymentlogmodel',
            name='installment_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, to='installments.installmentnumbermodel'),
        ),
    ]
