# Generated by Django 4.0.3 on 2022-11-20 00:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('installments', '0009_installmentmodel_received'),
        ('finance', '0006_remove_paymentlogmodel_installment_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ManufacturerTotalPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.FloatField(max_length=7)),
                ('timePaid', models.DateTimeField(auto_now_add=True)),
                ('installment_id', models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, to='installments.installmentnumbermodel')),
                ('user_id', models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
