# Generated by Django 4.0.3 on 2022-11-20 12:15

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('installments', '0009_installmentmodel_received'),
        ('finance', '0007_manufacturertotalpayment'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ManufacturerTotalPayment',
            new_name='TotalPayment',
        ),
    ]
