# Generated by Django 4.0.3 on 2022-11-20 15:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('installments', '0009_installmentmodel_received'),
        ('finance', '0008_rename_manufacturertotalpayment_totalpayment'),
    ]

    operations = [
        migrations.CreateModel(
            name='ManufacturerShippingPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.FloatField(max_length=7)),
                ('installment', models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, to='installments.installmentmodel')),
            ],
        ),
    ]
