# Generated by Django 4.0.3 on 2022-11-08 19:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('installments', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='installmentnumbermodel',
            name='user_id',
        ),
        migrations.AddField(
            model_name='installmentnumbermodel',
            name='user_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, to=settings.AUTH_USER_MODEL),
        ),
    ]
