# Generated by Django 4.0.3 on 2022-11-13 15:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('installments', '0003_remove_installmentnumbermodel_user_id_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='installmentmodel',
            old_name='product_id',
            new_name='productId',
        ),
    ]
