# Generated by Django 4.0.3 on 2022-11-17 06:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_initial'),
        ('installments', '0006_installmentnumbermodel_balance'),
    ]

    operations = [
        migrations.CreateModel(
            name='ManufacturerInstallmentRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField()),
                ('productId', models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, to='product.productsmodel')),
            ],
        ),
    ]
