# Generated by Django 4.0.3 on 2022-11-19 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('installments', '0007_manufacturerinstallmentrecord'),
    ]

    operations = [
        migrations.AddField(
            model_name='installmentmodel',
            name='approved',
            field=models.BooleanField(default=False),
        ),
    ]
