# Generated by Django 4.0.3 on 2022-11-19 22:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('installments', '0008_installmentmodel_approved'),
    ]

    operations = [
        migrations.AddField(
            model_name='installmentmodel',
            name='received',
            field=models.BooleanField(default=False),
        ),
    ]
