# Generated by Django 4.0.3 on 2022-11-07 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LandRegisterModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country', models.CharField(max_length=255)),
                ('sub_county', models.CharField(max_length=255)),
                ('village', models.CharField(max_length=255)),
                ('landSize', models.IntegerField()),
            ],
        ),
    ]
