# Generated by Django 4.0.3 on 2022-11-17 08:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('installments', '0007_manufacturerinstallmentrecord'),
        ('shipping', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shippingregister',
            name='installment',
        ),
        migrations.AddField(
            model_name='shippingregister',
            name='installment',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, to='installments.installmentnumbermodel'),
        ),
    ]
