# Generated by Django 4.0.3 on 2022-11-17 09:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shipping', '0002_remove_shippingregister_installment_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shippingregister',
            name='Shipping_status',
        ),
    ]
