# Generated by Django 4.0.3 on 2022-11-17 19:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shipping', '0004_shippingregister_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shippingregister',
            name='user',
        ),
    ]
